openapi: 3.0.0
info:
 description: This API provides audit info
 version: "1.0.0"
 title: Audit API
 contact:
    email: michaelnparker@gmail.com
paths:
 /air_quality:
    get:
     summary: gets an air quality reading from history
     operationId: app.get_air_quality_reading
     description: Gets air quality readings from the event store
     parameters:
      - name: index
        in: query
        description: Gets the AQ at the index in the event store
        schema:
            type: integer
            example: 100
     responses:
            '200':
                description: Successfully returned an air quality event
                content:
                    application/json:
                     schema:
                      type: object
                      items:
                         $ref: '#/components/schemas/AirQualityReading'
            '400':
                 description: Invalid request
                 content:
                    application/json:
                        schema:
                            type: object
                            properties:
                             message:
                                type: string
            '404':
                 description: Not Found
                 content:
                     application/json:
                        schema:
                            type: object
                            properties:
                                message:
                                    type: string
 /env_quality:
   get:
    summary: gets an envrionment quality reading from history
    operationId: app.get_env_reading
    description: Gets an environment reading from the event store
    parameters:
     - name: index
       in: query
       description: Gets the ER at the index in the event store
       schema:
         type: integer
         example: 100
    responses:
        '200':
            description: Successfully returned a environment reading event
            content:
                application/json:
                    schema:
                        type: object
                        items:
                         $ref: '#/components/schemas/EnvironmentReading'
        '400':
            description: Invalid request
            content:
                application/json:
                    schema:
                     type: object
                     properties:
                        message:
                            type: string
        '404':
            description: Not Found
components:
  schemas:
    AirQualityReading:
      required:
        - sensor_id
        - so2
        - co
        - no2
        - timestamp
      properties:
        sensor_id:
          type: string
          format: uuid
          example: c7dc66ec-61d6-488f-ba09-fe1cc87fff67
        so2:
          type: number
          example: 0.23
        co:
          type: number
          example: 0.00033
        no2:
          type: number
          example: 0.00233
        timestamp:
          type: string
          format: date-time
          example: '2017-11-29T03:45:26.001Z'
      type: object

    EnvironmentReading:
        required:
          - sensor_id
          - humidity
          - temp
          - wind_speed
          - wind_dir
          - timestamp
        properties:
          sensor_id:
            type: string
            format: uuid
            example: c7dc66ec-61d6-488f-ba09-fe1cc87fff67
          humidity:
            type: number
            example: 0.23
          temp:
            type: number
            example: 15.6
          wind_speed:
            type: number
            example: 45.6
          wind_dir:
            type: integer
            example: 127
          timestamp:
            type: string
            format: date-time
            example: '2017-11-29T03:45:26.001Z'
        type: object
